server:
  port: 8080

spring:
  application:
    name: small-grammar
  profiles:
    active: dev

grammar:
  core:
    poolSize: 1000
    stringIntern: true
  parser:
    cacheSize: 100
    validateRules: true
  compiler:
    optimizationLevel: 2
    convertToDFA: true
    minimizeDFA: true
  matcher:
    fuzzyMatch: true
    fuzzyThreshold: 0.8
    maxAlternatives: 3
    parallelism: 4
  rules:
    path: "src/resources/"
    hotReload: true
    reloadInterval: 60

logging:
  level:
    com.grammar: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"